baseURL = "/"
title = "rexarski"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "a playground"
  copyright = "Copyright © 2022 rexarski"
  dark = "auto"
  highlight = true

[menu]
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "posts"
  #   title = "posts"
  #   url = "/"
  #   weight = 10

  [[menu.main]]
    identifier = "blogs"
    name = "blog"
    title = "blog"
    url = "https://qrui.xyz"
    weight = 10

  # [[menu.main]]
  #   identifier = "about"
  #   name = "about"
  #   title = "about"
  #   url = "/about/"
  #   weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
